/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "../frontend/templates/**/*.{html,js}",
    "../frontend/static/js/**/*.js",
    "../frontend/static/css/**/*.css"
  ],
  safelist: [
    'hero-bg',
    'hero-overlay',
    'text-text-light',
    'text-bg-dark',
    'bg-accent',
    'bg-dark',
    'icon-base',
    'icon-hover',
    'icon-link',
    'flex',
    'flex-col',
    'justify-center',
    'items-center',
    'justify-between',
    'text-white',
    'text-4xl',
    'sm:text-5xl',
    'lg:text-7xl',
    'text-lg',
    'sm:text-xl',
    'lg:text-2xl',
    'min-h-screen',
    'relative',
    'w-full',
    'h-full',
    'z-10',
    'text-center',
    'font-bold',
    'mb-4',
    'mb-8',
    'px-8',
    'py-4',
    'rounded',
    'hover:bg-opacity-80',
    'transition',
    'shadow-md',
    'max-w-xs',
    'sm:max-w-sm',
    'lg:max-w-md',
    'space-x-3',
    'space-x-6',
    'px-6',
    'py-4',
    'max-w-7xl',
    'mx-auto',
    'absolute',
    'top-0',
    'left-0',
    'bg-transparent',
    'z-20'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-dark': '#282a36',
        'accent': '#bd93f9',
        'text-light': '#f8f8f2',
      },
    },
  },
  plugins: [],
}