name: Railway Service Down

on:
  workflow_dispatch:

jobs:
  railway-down:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Derrubar serviço (0 réplicas)
        run: railway scale 091b247d-e42f-488d-a5ef-de49f997dd1d 0
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: 20cf59a4-f179-4e70-adca-42c06360986c
          RAILWAY_ENVIRONMENT_ID: 78256919-3101-408d-874d-e60d6f4e63b4